language: python
python:
- '3.6'
install:
- pip install 'molecule[gce]' paramiko
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
  global:
  - secure: fyOaV0Wbobk/ciQSQvugmz+ia7PD0dFw/X5DuqvHWnxYMgk8CVvuQG/h+fpWP/VjWBNhKmdOaB6SGoUu46YPPMdj1tjvIm61LBIm83T67hqKyxLsRnzcCQonlXhNho4DljWtXWg2//zlsBmoIN4T/ykgVJeinY+BXnPqFJB0PF6RjuU8ECb33zNkmQl7BRkExv3YUx9pbaVJ8TYM/n6s0ON7vJid0GHTPGUWHmqnxpxwHK17VGsfjbqOXclksAgNsfyRk4swOuuna5EvwGqz1+RSJ16KD9QHgtho/bntf0YZ5Amw8FVq+iDSZfygXVbKkYPav/23iCpGjdj1ohKtN9vyf3KU0evkdWWZVzuNvo/j3TCwNUtrYWNWnGPpW8tCvfjkvkBQzRd7qPBkfjORnfs0FV4anKOSPoRE4AYpXkBrRuZ5mGl6rMny8hjmtIGK7STnV3nipaaof8sDoe7kh0C0CS2cEwcrQZHSgXp0zfEqZP0R5RaJrIbUX6szNmvd2zeUoQ/+DmMXVMG7keC01Qx5YQNN0x8xzkS3YcL/onL1oLwb/URMeNlXEghNHXa0yy0ed9pbLQSVyQbrrZGdvDhXKJhU+018rGs2HG2Ke5fPtCSxtwXKIDsq+siXb8V693I/calQ2ZJe1l5vAX0M1wEfOBq/DibuW8SrqrISWHA=
  - secure: HHpGv/KE9DFGlliFqJtvq8eO/jz878MWZCJ2+TwbfkPylKa7wO9TJF0005HPZO1pBgEkzM1dkIk0eYAg5CwYZ93RB3gY9buR3SFrtLSyuM4l9Z0t8vML7jvRaUd5RJcYZTgARBbukW9FNWR9huFipccZZnsIGUGmpmjaHrJI7j+ttqP/B8Iy9xfOAjeut5I3u6RggwUIMnRFS27ockEw3JSje4NsZaRixZIYkfKblmh6Bk3NlqcWvPOrrArWnHIDkDmsSl7z4GlWnzmzizmOgoM43cBTtBen9sVPq2smnjIMn3EACWUzIbe45+ztmeiKnAgVFp/qD2n4Coh/1JYCUPqKatel7L6ZqbjKZpROfgww+WBhV8IFVz7Vm+vp2W//twO7REP2nEzKflgckm1/Z07mtOHk7sWObH75beUcFdarHVB+i+ICnOh50ETRF1us711bO1nCUwDpy5bLXRPcjMub9qzboW/xDM2V1RRW/vPe6jSq60RbdQHauuOuyLyBfkh4XWapPs83VdhSIJymhSH7PBj0J6uaC+aML0Ehne7T6jnEsXkkxsqlP8pUiR5iHG1aKLCPK9Wf3VSGTKvsZhIALg5HxZb6hjEQhBYHbs0L+bSWtotUwiMVfvbfm3WEDTDF+r3IbGC15ICLOmN9dLC0uEAz8RH0XMZU5uvQJp8=
  - secure: Hoz04IwPt6OrzuZTycgSZeH6Vpu86CQ0gSLQN29pz4DW5e6rife8/A+lSticyQV85bZPvgtEwE+pmnZfQxH+TRYItNDkFjTqOk4xMgvfGuU+A5ePA3xIFbECI1d0p5lyNDJmXixgEWWM+Byl2U+q6fhsqFTInPP1njvsAWhiGWyoXngpB5qMfAzptZwef6BbtEZ46XWQWVG43ncxld4DXdmsoRSNlgfJpXxlqLcoQzkt/GAT3Wn5lXVmD5IWZ5vVAGOZ9zGLmZP4gGUD3MU5fXHPIWDXVUfywVz2QxNbPurahGk/JU/wZ16193IikzFxezvowyWQa/zqEbvLd0f7BIRsBlgc0+ieFW1tcUDiDBg1ia1kDyChg1On2a66kGjKHSHICGBagjd9wsuvGIk0bkYAHTYsMB+QAzl6GnltGylpQwKdmU6i7QIg3/95kKb0E6rqjb0rSbPxDQfW6crlG47YG4wJzVW11GS6wYgeFR94VS6xHLozXjs23aKJGSc39vnlhYmxIWCTEdYUOM6QNgoYirWzftAi8zF9jnL4MEJGX8iLp0bt2FZBa0sjdv+90bC6d/ObuOIVcOD0fFrbXd4PI9PZ0LT3WFxUsbcpWR+Sa2eAg8cpPJRprCj7tDHuLVduPsjApkhiGx7rutzoQ6fAcg7wY+VgZo2Ek2BrFFs=
before_install:
- openssl aes-256-cbc -K $encrypted_dab79c4f5f0a_key -iv $encrypted_dab79c4f5f0a_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- chmod 0600 google_compute_engine
script:
- molecule create
- molecule converge
- molecule verify
after_script:
- molecule destroy
notifications:
  slack:
    rooms:
      secure: UQ1LVaqGBY/RVOs5sEiVEHjKu3R+N0qMz8IxeNy0qKM+EdABYtOijzCB249qrYA+yFvX3sPkpWN8fEzJ5wbYloZy64RHL2PB9I+JsQBJZtBaCXvcyp/u+QmFnqYO3TbHMU/anBjwRHIN3wI5hkflBNZElG2ANM1lAMqIv5yt4cPGZuwnwT92m8qcoRUbzB1X3VzmNuA4sw+RHu6Jj8jK7H3Zy75D690wUwK2gOdHuGaKh6oyTtt8bo8FijH80CxDsGwkMbPYT5RGEUagn/R8K1PCjaTk4jqD0oePi14b6UQJ88/Tt4hKZIkGnZhEYgeni5wL0Ip4W1qeimdr1PKW6fo/F8Wj6LE/unko1GA+oPJNXkFS+ft6RHQNOVvgf7yv13/cYdDYnrHRqlt+4qFk59wNP82amIPvxdGpOTwYUSEanaZBi9lFW9ElkxNH6ICiDfrNu3BzTa729Cj21+YyKvYDXlayZzhStILUDysAlqC3op6iFG5iSCdYo0VqjQVNTuyRi1cgvBfgJS+PEVAolQtbSu67CIhIdPATdiWvdGGbZtquSQBLLuJcy3Wj/DnGnO802B5IwC3hJ0AF6sXBVldLvNJguaApPoMyHtLQ1nLN5XKxzOg0KRWY8raHUGJx8k7ZtkTWoAg7Px6yU8nKazkOXzOJMwsSXnePUAZ8BQ0=
